// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
//
// TODO(setup): Run `flutterfire configure` to replace this placeholder
// with your actual Firebase project configuration.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not configured for ${defaultTargetPlatform.name}. '
          'Run `flutterfire configure` to generate this file.',
        );
    }
  }

  // TODO(setup): Replace these placeholder values after running
  // `flutterfire configure`. The CLI will overwrite this entire file.

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCleynG97H14xwoeQPyBkYakkuIC1wGcq4',
    appId: '1:593793808284:android:bc2683e1816b61f2b0ba59',
    messagingSenderId: '593793808284',
    projectId: 'engram-26a3a',
    storageBucket: 'engram-26a3a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTkhmUcpNCLT6JrJOOIC3RV8t7x-lRiLs',
    appId: '1:593793808284:ios:8c647ab5e614a11db0ba59',
    messagingSenderId: '593793808284',
    projectId: 'engram-26a3a',
    storageBucket: 'engram-26a3a.firebasestorage.app',
    androidClientId:
        '593793808284-p1ijmejeqep15lburbkgfirsh1r63dje.apps.googleusercontent.com',
    iosClientId:
        '593793808284-3lici2b3q9a9aakq5deullkh94a23b87.apps.googleusercontent.com',
    iosBundleId: 'co.enspyr.engram',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTkhmUcpNCLT6JrJOOIC3RV8t7x-lRiLs',
    appId: '1:593793808284:ios:8c647ab5e614a11db0ba59',
    messagingSenderId: '593793808284',
    projectId: 'engram-26a3a',
    storageBucket: 'engram-26a3a.firebasestorage.app',
    androidClientId:
        '593793808284-p1ijmejeqep15lburbkgfirsh1r63dje.apps.googleusercontent.com',
    iosClientId:
        '593793808284-3lici2b3q9a9aakq5deullkh94a23b87.apps.googleusercontent.com',
    iosBundleId: 'co.enspyr.engram',
  );
}
